### ISSUE TITLE
Update to graphviz 9.0

### ISSUE THREAD

**Issue by Naikless** [conda-forge/.github#494]
### Comment:

Is there already a timeframe for updating this recipe to graphviz 9.0? Or are there any blockages on the way? 

9.0 includes a bugfix for displaying edges with multiple arrowheads that I would like to include in my conda environment.

**Comment by hmaarrfk** [comment]
Somebody must champion addressing the windows build failures of https://github.com/conda-forge/graphviz-feedstock/pull/128

please discuss on that feedstock.

I'm going to close because there is no "action" to be taken by others. Help in the builds is welcome. Anybody can fork and make a working PR for it to be reviewed.
